---
version: 2
updates:
  # if you've got poetry / a requirements.txt, uncomment this
  # - package-ecosystem: pip
  #   directory: /
  #   schedule:
  #     interval: weekly
  #     day: saturday
  #     time: "02:00"
  #     timezone: "Australia/Brisbane"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: "Australia/Brisbane"
